-- SE IMPORTA UN PAQUETE PLSQL
-- HABILITA LA SALIDA POR PANTALLA
SET SERVEROUTPUT ON

BEGIN

DBMS_OUTPUT.PUT_LINE(100);
-- *************** CON || SE CONCATENAN STRINGS *******************
DBMS_OUTPUT.PUT_LINE('SDSFSF' || 'HOLA');

END;